FROM python:3.8.10 AS build 

WORKDIR /app

# Install dependencies
COPY ./requirements.txt /app/
RUN python -m venv venv
RUN /app/venv/bin/pip install -r requirements.txt

FROM build

COPY . /app

EXPOSE 5000

CMD ["/app/venv/bin/python", "orchestrator.py"]
