version: "3.9"
services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - "1883:1883"

  node1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ID=1

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ID=2

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ID=3
