version: "3.9"
services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ID=1
    ports:
      - "5001:5000"
  node2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ID=2
    ports:
      - "5002:5000"
  node3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ID=3
    ports:
      - "5003:5000"



# dans l'orchestrateur passer l'ensemble des noeuds avec leur ports 