# Utiliser une image de base Python
FROM python:3.9-slim

# Installer les dépendances nécessaires
WORKDIR /app

# Copier le code source dans l'image
COPY . .

# Exposer le port (sera remplacé par des variables d'environnement)
# EXPOSE 5500

# Définir la commande de démarrage
# CMD ["python", "nodes.py"]
